# -*- coding: utf-8 -*-
"""
test_ifc_golden_dependency_honesty.py

Tests that the IFC golden fixture path preserves the honesty contract
regardless of whether ifcopenshell is installed. Probes both branches
of the extraction gate.
"""

import sys
import types
from pathlib import Path

import pytest

from src.engine.extractors.ifc_extractor import IFCExtractor
from src.tests.fixtures.ifc.fake_models import FakeModel, make_fake_ifcopenshell


def test_golden_fixture_file_exists_and_is_immutable():
    """The .ifc file on disk exists with stable content."""
    fixture_dir = Path(__file__).resolve().parent / "fixtures" / "ifc" / "golden_v1"
    fixture_path = fixture_dir / "ifc_simple_building.ifc"
    assert fixture_path.exists(), f"Missing golden fixture: {fixture_path}"
    data = fixture_path.read_bytes()
    assert len(data) == 1213, "Fixture size changed: %d" % len(data)
    # File must start with ISO-10303-21 HEADER marker
    assert b"ISO-10303-21" in data, "Not a valid IFC STEP file"
    assert b"IFC2X3" in data, "Not an IFC2x3 schema file"


def test_fake_models_module_is_importable():
    """Shared test doubles are accessible from the fixtures package."""
    from src.tests.fixtures.ifc.fake_models import FakeEntity, FakeConnection, FakeModel
    model = FakeModel()
    assert model.project.is_a("IfcProject")
    assert model.site.is_a("IfcSite")
    assert model.product.is_a("IfcWall")
    conn = model.connection
    assert conn.is_a("IfcRelConnectsElements")
    assert conn.RelatingElement.GlobalId == "wall-guid-001"
    assert conn.RelatedElement.GlobalId == "slab-guid-002"


def test_extract_with_fake_ifcopenshell_emits_contract_types():
    """Using the shared fake_models module, extraction emits exactly the four contract types."""
    fake_model = FakeModel()
    make_fake_ifcopenshell(fake_model)

    try:
        result = IFCExtractor().extract("model.ifc")
        assert result.success is True
        record_types = {r["type"] for r in result.records}
        assert record_types == {
            "ifc_project",
            "ifc_spatial",
            "ifc_element_metadata",
            "ifc_connection",
        }
        # Every record has entity in provenance
        for rec in result.records:
            assert rec["provenance"].get("entity"), \
                "Record missing provenance.entity: %s" % rec["type"]
    finally:
        # Clean up monkeypatched modules
        for mod_name in list(sys.modules.keys()):
            if mod_name.startswith("ifcopenshell"):
                del sys.modules[mod_name]


def test_extract_without_ifcopenshell_fails_honestly_on_golden_fixture(tmp_path):
    """Honest failure on the real golden fixture when ifcopenshell is absent."""
    import builtins
    real_import = builtins.__import__

    def guarded_import(name, globals=None, locals=None, fromlist=(), level=0):
        if name == "ifcopenshell" or name.startswith("ifcopenshell."):
            raise ImportError("simulated missing ifcopenshell")
        return real_import(name, globals, locals, fromlist, level)

    builtins.__import__ = guarded_import
    try:
        fixture_dir = Path(__file__).resolve().parent / "fixtures" / "ifc" / "golden_v1"
        fixture_path = fixture_dir / "ifc_simple_building.ifc"
        result = IFCExtractor().extract(str(fixture_path))

        assert result.success is False
        assert result.records == []
        diag = "\n".join(result.diagnostics).lower()
        assert "ifcopenshell" in diag
        assert "missing" in diag or "unavailable" in diag
        # Honest failure explicitly states "no fallback" — that's the contract
        assert "no fallback" in diag or "disabled" in diag, \
            "Missing: explicit 'no fallback' statement in diagnostics: %s" % diag
        # No regex/text fallback claim
        assert "regex/text" not in diag
        assert "good enough" not in diag
    finally:
        builtins.__import__ = real_import


def test_golden_fixture_is_not_a_mock_or_fake_file():
    """The golden .ifc is a real STEP file, not generated by fake objects."""
    fixture_path = Path(__file__).resolve().parent / "fixtures" / "ifc" / "golden_v1" / "ifc_simple_building.ifc"
    content = fixture_path.read_text(encoding="utf-8")
    # Must follow STEP/IFC text format
    assert content.startswith("ISO-10303-21;")
    assert "HEADER;" in content
    assert "ENDSEC;" in content
    assert "DATA;" in content
    assert "END-ISO-10303-21;" in content
    # Must contain IFC entity definitions
    assert "IFCPROJECT" in content
    assert "IFCWALL" in content
    assert "IFCSITE" in content
    assert "IFCBUILDING" in content
    assert "IFCBUILDINGSTOREY" in content


def test_golden_fixture_has_no_programmatic_generators():
    """The golden fixture is a static file, not produced at test time."""
    fixture_path = Path(__file__).resolve().parent / "fixtures" / "ifc" / "golden_v1" / "ifc_simple_building.ifc"
    # File age check: it was committed, not generated per-test
    # (This test is a policy guard — if someone accidentally makes this a
    #  generate-each-run script, the file size or content would drift.)
    data = fixture_path.read_bytes()
    assert len(data) == 1213, "Fixture size changed — re-generate and update MANIFEST.md"
