
import customtkinter as ctk
import os

class FactLineagePopup(ctk.CTkToplevel):
    def __init__(self, parent, db, fact_id):
        super().__init__(parent)
        self.title(f"Lineage: {fact_id}")
        self.geometry("700x500")
        self.db = db
        self.fact_id = fact_id
        self.geometry("700x500")

        self.draw_lineage()

    def draw_lineage(self):
        # 1. Get Fact Info (Correct Schema)
        row = self.db.execute("""
            SELECT fact_type, subject_id, COALESCE(value_text, CAST(value_num AS TEXT), value_json), as_of_json, created_at, method_id, location_json
            FROM facts WHERE fact_id=?
        """, (self.fact_id,)).fetchone()

        if not row:
            ctk.CTkLabel(self, text="Fact not found", text_color="red").pack(pady=20)
            return

        fact_type, subject_id, val_str, as_of_json, created_at, method_id, location_json = row
        val_str = str(val_str)[:50]

        # Parse evidence location from location_json
        import json
        page_no = None
        bbox = None
        try:
            loc = json.loads(location_json) if isinstance(location_json, str) else (location_json or {})
            if isinstance(loc, dict):
                page_no = loc.get("page") or loc.get("page_or_slide")
                bbox = loc.get("bbox")
        except Exception:
            pass

        location_label = ""
        if page_no:
            location_label = f" page {page_no}"
            if bbox and isinstance(bbox, (list, tuple)) and len(bbox) >= 4:
                location_label += f" [{int(bbox[0])},{int(bbox[1])}-{int(bbox[2])},{int(bbox[3])}]"

        # Main Container
        canvas = ctk.CTkScrollableFrame(self, fg_color="#1a1a1a")
        canvas.pack(fill="both", expand=True, padx=20, pady=10)

        # --- Node 1: The Fact ---
        self._draw_node(canvas, "FACT (The Truth)", f"{fact_type}\n{subject_id}\nValue: {val_str}", "green")

        self._draw_arrow(canvas, f"Generated by {method_id}")

        # --- Node 2: The Context (As-Of) ---
        file_ver_id = None
        try:
            as_of = json.loads(as_of_json)
            if as_of.get("type") == "file":
                file_ver_id = as_of.get("snapshot_id")
        except Exception:
            pass

        if file_ver_id:
            f_row = self.db.execute("SELECT source_path, file_ext, size_bytes FROM file_versions WHERE file_version_id=?", (file_ver_id,)).fetchone()
            if f_row:
                fname = os.path.basename(f_row[0])
                content_lines = [f"{fname}", f"{f_row[1]} | {f_row[2]} bytes"]
                if location_label:
                    content_lines.append(f"Location:{location_label}")
                self._draw_node(canvas, "SOURCE FILE (Evidence)", "\n".join(content_lines), "#1f538d")

                # Show full path
                ctk.CTkLabel(canvas, text=f"Full Path: {f_row[0]}", text_color="gray", font=("Consolas", 10)).pack(pady=(0, 5))

                # Buttons to open source
                btn_frame = ctk.CTkFrame(canvas, fg_color="transparent")
                btn_frame.pack(pady=(5, 10))

                btn_open_source = ctk.CTkButton(
                    btn_frame,
                    text=f"Open Source File",
                    height=26,
                    width=140,
                    command=lambda fp=f_row[0], p=page_no: self._open_source_file(fp, p),
                )
                btn_open_source.pack(side="left", padx=5)

                btn_inspector = ctk.CTkButton(
                    btn_frame,
                    text=f"File Inspector (p.{page_no})",
                    height=26,
                    width=170,
                    command=lambda fp=f_row[0], fid=None, p=page_no: self._open_inspector(fp, p),
                )
                btn_inspector.pack(side="left", padx=5)
            else:
                self._draw_node(canvas, "Unknown Source", f"ID: {file_ver_id}", "gray")
        else:
             self._draw_node(canvas, "System / Inferred", "No direct file source", "gray")

    def _open_source_file(self, file_path: str, page_no):
        """Open the source file, attempting page-aware navigation for PDFs."""
        import platform
        import subprocess
        if page_no and str(file_path).lower().endswith(".pdf"):
            import shutil
            candidates = [
                r"C:\Program Files\Adobe\Acrobat DC\Acrobat\AcroRd32.exe",
                r"C:\Program Files (x86)\Adobe\Acrobat DC\Acrobat\AcroRd32.exe",
            ]
            reader = None
            for c in candidates:
                if os.path.isfile(c):
                    reader = c
                    break
            if not reader:
                reader = shutil.which("AcroRd32.exe")
            if reader:
                try:
                    subprocess.Popen([reader, "/A", f"page={page_no}", file_path], shell=False)
                    return
                except Exception:
                    pass
        os.startfile(file_path)

    def _open_inspector(self, file_path: str, page_no):
        """Open the File Inspector, optionally at a specific page."""
        from src.ui.panels.file_detail_panel import FileDetailPanel
        FileDetailPanel(self, self.db, file_path=file_path, page_no=page_no)

    def _draw_node(self, parent, title, content, color):
        f = ctk.CTkFrame(parent, fg_color=color, corner_radius=10)
        f.pack(fill="x", padx=50, pady=5)

        ctk.CTkLabel(f, text=title, font=("Arial", 12, "bold"), text_color="white").pack(pady=(10, 5))
        ctk.CTkLabel(f, text=content, font=("Consolas", 12), text_color="white").pack(pady=(0, 10))

    def _draw_arrow(self, parent, label):
        ctk.CTkLabel(parent, text="|", font=("Arial", 20, "bold"), text_color="gray").pack()
        ctk.CTkLabel(parent, text=label, font=("Arial", 10), text_color="gray").pack(pady=(0, 10))
