
import customtkinter as ctk
import os

class FactLineagePopup(ctk.CTkToplevel):
    def __init__(self, parent, db, fact_id):
        super().__init__(parent)
        self.title(f"Lineage: {fact_id}")
        self.geometry("600x400")
        self.db = db
        self.fact_id = fact_id
        
        self.draw_lineage()
        
    def draw_lineage(self):
        # 1. Get Fact Info (Correct Schema)
        # Schema: fact_id, fact_type, subject_id, as_of_json, value_text, value_num
        row = self.db.execute("""
            SELECT fact_type, subject_id, COALESCE(value_text, CAST(value_num AS TEXT), value_json), as_of_json, created_at, method_id
            FROM facts WHERE fact_id=?
        """, (self.fact_id,)).fetchone()
        
        if not row:
            ctk.CTkLabel(self, text="Fact not found", text_color="red").pack(pady=20)
            return

        fact_type, subject_id, val_str, as_of_json, created_at, method_id = row
        val_str = str(val_str)[:50]
        
        # Main Container
        canvas = ctk.CTkScrollableFrame(self, fg_color="#1a1a1a")
        canvas.pack(fill="both", expand=True, padx=20, pady=20)
        
        # --- Node 1: The Fact ---
        self._draw_node(canvas, "FACT (The Truth)", f"{fact_type}\n{subject_id}\nValue: {val_str}", "green")
        
        self._draw_arrow(canvas, f"Generated by {method_id}")
        
        # --- Node 2: The Context (As-Of) ---
        import json
        file_ver_id = None
        try:
            as_of = json.loads(as_of_json)
            # Typically {type: 'file', snapshot_id: '...'}
            if as_of.get("type") == "file":
                file_ver_id = as_of.get("snapshot_id")
        except:
            pass
            
        if file_ver_id:
            # Get File Info
            f_row = self.db.execute("SELECT source_path, file_ext, size_bytes FROM file_versions WHERE file_version_id=?", (file_ver_id,)).fetchone()
            if f_row:
                fname = os.path.basename(f_row[0])
                self._draw_node(canvas, "SOURCE FILE (Evidence)", f"{fname}\n{f_row[1]} | {f_row[2]} bytes", "#1f538d") # Blue
                
                # Link to File Detail (Optional: could add button here)
                ctk.CTkLabel(canvas, text=f"Full Path: {f_row[0]}", text_color="gray", font=("Consolas", 10)).pack(pady=5)
            else:
                self._draw_node(canvas, "Unknown Source", f"ID: {file_ver_id}", "gray")
        else:
             self._draw_node(canvas, "System / Inferred", "No direct file source", "gray")

    def _draw_node(self, parent, title, content, color):
        f = ctk.CTkFrame(parent, fg_color=color, corner_radius=10)
        f.pack(fill="x", padx=50, pady=5)
        
        ctk.CTkLabel(f, text=title, font=("Arial", 12, "bold"), text_color="white").pack(pady=(10, 5))
        ctk.CTkLabel(f, text=content, font=("Consolas", 12), text_color="white").pack(pady=(0, 10))
        
    def _draw_arrow(self, parent, label):
        ctk.CTkLabel(parent, text="↑", font=("Arial", 20, "bold"), text_color="gray").pack()
        ctk.CTkLabel(parent, text=label, font=("Arial", 10), text_color="gray").pack(pady=(0, 10))
